name: Pull request auto add label workflow
on:
  workflow_call:
    secrets:
      gh_app_id:
        required: true
      gh_app_private_key:
        required: true

permissions: {}
jobs:
  auto-add-label:
    runs-on: ubuntu-latest
    permissions: {}
    if: >-
      github.event.pull_request.user.login != 'renovate[bot]' &&
      contains(github.head_ref, 'feat') ||
      contains(github.head_ref, 'fix') ||
      contains(github.head_ref, 'test') ||
      contains(github.head_ref, 'doc')
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
        with:
          app_id: ${{secrets.gh_app_id}}
          private_key: ${{secrets.gh_app_private_key}}
      - run: |
          if [[ "$HEAD_REF" == *"feat"* ]]; then
            echo "HEADブランチに 'feat' が含まれています。"
            gh -R "$GITHUB_REPOSITORY" pr edit "$PR_NUMBER" --add-label "feature"
          elif [[ "$HEAD_REF" == *"fix"* ]]; then
            echo "HEADブランチに 'fix' が含まれています。"
            gh -R "$GITHUB_REPOSITORY" pr edit "$PR_NUMBER" --add-label "fix"
          elif [[ "$HEAD_REF" == *"test"* ]]; then
            echo "HEADブランチに 'test' が含まれています。"
            gh -R "$GITHUB_REPOSITORY" pr edit "$PR_NUMBER" --add-label "test"
          elif [[ "$HEAD_REF" == *"doc"* ]]; then
            echo "HEADブランチに 'doc' が含まれています。"
            gh -R "$GITHUB_REPOSITORY" pr edit "$PR_NUMBER" --add-label "documentation"
          fi
        env:
          GITHUB_TOKEN: ${{steps.generate_token.outputs.token}}
          PR_NUMBER: ${{github.event.pull_request.number}}
          HEAD_REF: ${{github.head_ref}}