name: Pull Request
on: pull_request

jobs:
  auto-merge:
    permissions:
      contents: read
    uses: murn0/renovate-automerge-workflow/.github/workflows/main.yaml@62601a0f42abc4f6ae725d1d4fa1cdcc6ca914be # v0.4.0
    with:
      filters: |
        ghalint:
          - .github/workflows/*.yaml
          - aqua/aqua.yaml
          - aqua/imports/ghalint.yaml
          - ghalint.yaml
        renovate-config-validator:
          - renovate.json
          - .github/workflows/pull_request.yaml
        update-aqua-checksums:
          - aqua/aqua.yaml
          - aqua/imports/*.yaml
          - aqua/aqua-checksums.json
          - .github/workflows/pull_request.yaml
    secrets:
      gh_app_id: ${{secrets.GH_APP_ID}}
      gh_app_private_key: ${{secrets.GH_APP_PRIVATE_KEY}}