name: Pull Request
on: pull_request

jobs:
  auto-merge:
    permissions:
      contents: read
    uses: murn0/renovate-automerge-workflow/.github/workflows/main.yaml@c8427d93a3a906a38a7cb6e0e09630704fe760bb # v0.3.0
    with:
      filters: |
        ghalint:
          - .github/workflows/*.yaml
          - aqua/aqua.yaml
          - aqua/imports/ghalint.yaml
          - ghalint.yaml
        renovate-config-validator:
          - renovate.json
          - .github/workflows/main.yaml
          - .github/workflows/wc-renovate-config-validator.yaml
        update-aqua-checksums:
          - aqua/aqua.yaml
          - aqua/imports/*.yaml
          - aqua/aqua-checksums.json
          - .github/workflows/main.yaml
          - .github/workflows/wc-update-aqua-checksums.yaml
    secrets:
      gh_app_id: ${{secrets.GH_APP_ID}}
      gh_app_private_key: ${{secrets.GH_APP_PRIVATE_KEY}}